//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpellChecker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spell()
        {
            this.UserSpells = new HashSet<UserSpell>();
        }
    
        public int SpellId { get; set; }
        public string SpellName { get; set; }
        public int SpellLevel { get; set; }
        public string SpellSchool { get; set; }
        public string CastingTime { get; set; }
        public string SpellRange { get; set; }
        public bool VComponents { get; set; }
        public bool SComponents { get; set; }
        public bool HasMComponents { get; set; }
        public string MComponents { get; set; }
        public string Duration { get; set; }
        public string SpellText { get; set; }
        public string SpellSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSpell> UserSpells { get; set; }
    }
}
