//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpellChecker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSpell
    {
        public int UserSpellId { get; set; }
        public Nullable<int> SpellId { get; set; }
        public string UserId { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual Spell Spell { get; set; }
    }
}
